@URL_BASE=http://localhost:8080

### Obter todas as pessoas

GET {{URL_BASE}}/pessoa

### Obter pessoa pelo ID
GET {{URL_BASE}}/pessoa/10

### Obter todas pessoas por pagina
GET {{URL_BASE}}/pessoa?size=1&page=1&sort=email&direction=DESC

### Cadastrar 1 pessoa
POST {{URL_BASE}}/pessoa
Content-Type: application/json

{
    "nome": "Joao",
    "telefone": "", 
    "email": "joao2@gmail.com",
    "senha": "123",
    "nascimento": "1997-12-27",
    "cpf": "",
    "tipo": "0"
}